#!/bin/bash

###############################################################################
##
## QLIPP: Connecto to Wordpress Database
## =====================================
##
## Brief: This script will automatically connect to a wordpress database by
##        reading the wp-config.php file and connecting to the mysql database
##
## Changelog:
## ----------
##   2016-04-06 - Koen Hausmans : Initial version
##
###############################################################################

WORDPRESS_CONFIG=`find . -iname wp-config.php 2>/dev/null`

DB_NAME=`cat $WORDPRESS_CONFIG | grep 'DB_NAME' | awk -F"'" '{ print $4 }'`
DB_USER=`cat $WORDPRESS_CONFIG | grep 'DB_USER' | awk -F"'" '{ print $4 }'`
DB_PASSWORD=`cat $WORDPRESS_CONFIG | grep 'DB_PASSWORD' | awk -F"'" '{ print $4 }'`

mysql -u $DB_USER --password="$DB_PASSWORD" $DB_NAME

