#!/usr/bin/env bash
# Based on: https://github.com/holman/dotfiles/blob/master/script/bootstrap


## DO NOT CHANGE BELOW

# Enable unofficial bash strict mode
set -euo pipefail
IFS=$'\n\t'

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MODE_ARGUMENT=${1:-}

source "$BASEDIR/_helpers.sh"
source "$BASEDIR/_links.sh"

# Check for root permissions
if [ "$(whoami)" == "root" ] ; then
    fail "Please execute without root permissions!"
fi

DOTFILES_ROOT="$(dirname "$BASEDIR")"

install_dotfiles () {
    info 'installing dotfiles'

    local src dotfiles_name mode_dotfiles_file
    local -a links=()

    while IFS= read -r -d '' src
    do
        dotfiles_name=$(basename "${src%.*}")

        if [[ "$MODE_ARGUMENT" != "" ]] ; then
            mode_dotfiles_file="${src%.*}.$MODE_ARGUMENT"
            if [ -f "$mode_dotfiles_file" ] ; then
                src="$mode_dotfiles_file"
            fi
        fi

        links+=("$src" "$HOME/.$dotfiles_name")
    done < <(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*' -print0)

    link_files "${links[@]}"
}

install_dotfiles

echo
echo '  All installed!'
