#!/usr/bin/env bash
# Based on: https://github.com/holman/dotfiles/blob/master/script/install

## DO NOT CHANGE BELOW

# Enable unofficial bash strict mode
set -euo pipefail
IFS=$'\n\t'

# Set up helper functions for outputting to the command line
info () {
	printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
	printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
	echo ''
	exit
}

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_ROOT="$(dirname "$BASEDIR")"

info 'Running installer scripts'



find $DOTFILES_ROOT -iname install.sh -print0 | while IFS="" read -r -d "" installer
do
	ShortInstallerName=$(echo ${installer} | sed 's:/home/koen/.dotfiles/::g')
	info "Executing \e[1m${ShortInstallerName}\e[0m"

	# Disable immediate exit if a command fails, otherwise the check for exit codes does not work
	set +e

	sh -c "${installer}"
	if [ $? -ne 0 ] ; then
		fail "Error while executing \e[1m${ShortInstallerName}\e[0m"
	fi
done

