### ---------------------------------------------------------------------------
### General
### ---------------------------------------------------------------------------

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

shopt -s checkwinsize

set -o emacs

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

### ---------------------------------------------------------------------------
### Auto completion
### ---------------------------------------------------------------------------
shopt -s extglob
shopt -s globstar
shopt -s hostcomplete
shopt -s nocaseglob

bind "TAB:menu-complete"
bind "set show-all-if-ambiguous on"

# Load bash_completion (including git support)
[ -f /etc/bash_completion ] && . /etc/bash_completion
[ -f /etc/bash_completion.d/git-prompt ] && . /etc/bash_completion.d/git-prompt
[ -f /etc/bash_completion.d/git ] && . /etc/bash_completion.d/git

### ---------------------------------------------------------------------------
### Environment variables
### ---------------------------------------------------------------------------

if [[ $TERM == xterm ]] ; then
    TERM=xterm-256color
fi

export DOTFILES="$HOME/.dotfiles"

export PATH="$HOME/bin:$DOTFILES/bin:$HOME/.local/bin/:$PATH"

export VISUAL="vim"
export EDITOR="$VISUAL"

### ---------------------------------------------------------------------------
### Directories
### ---------------------------------------------------------------------------
shopt -s autocd
shopt -s cdspell
shopt -s cdable_vars
shopt -s dirspell

alias ls='ls --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

### ---------------------------------------------------------------------------
### Aliases
### ---------------------------------------------------------------------------

# Remove shortcuts
alias rr="rm -rf"

# Directory navigation aliases
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."

alias -- -='cd -'

# Ls aliases
alias lsa='ls -lah'
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -lAh'

# Git alias
alias g="git"
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit -a'
alias gcam='git commit -a -m'
alias gce='git commit -e'
alias gcm='git commit -m'
alias gco='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdt='git diff-tree --no-commit-id --name-only -r'
alias gl='git log --stat'
alias gpush='git push'
alias gpull='git pull --rebase'
alias gr='git remote'
alias gs='git status -sb'


# Output the week number
alias week="date +%V"

### ---------------------------------------------------------------------------
### Customization
### ---------------------------------------------------------------------------

export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUPSTREAM="auto"

SELECT="if [[ \$? != 0 ]]; then echo -e \"\[\033[01;31m\]\"; else echo -e \"\[\033[01;34m\]\" ; fi"
export PS1="\w \[\033[01;40;33m\]\$(__git_ps1 '(%s) ')\[\033[01;34m\]\$\[\033[00m\] "

export PS1="\`${SELECT}\`$PS1"

[[ -n "$SSH_CONNECTION" ]] && export PS1="\[\033[01;32m\]\u@\h\[\033[01;34m\] $PS1"

### ---------------------------------------------------------------------------
### History
### ---------------------------------------------------------------------------

set -o histexpand

shopt -s cmdhist
shopt -s histappend

HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

### ---------------------------------------------------------------------------
### FZF Plugin
### ---------------------------------------------------------------------------

if [[ -d "$HOME/.fzf" ]] ; then
    export PATH="$PATH:$HOME/.fzf/bin"
    export MANPATH="$MANPATH:$HOME/.fzf/man"

    [[ $- == *i* ]] && source "$HOME/.fzf/shell/completion.bash" 2> /dev/null

    source "$HOME/.fzf/shell/key-bindings.bash"
fi

### ---------------------------------------------------------------------------
### Z Plugin
### ---------------------------------------------------------------------------
Z_HOME="$HOME/.local/share/z/"
if [[ ! -d "$Z_HOME" ]] ; then
    git clone https://github.com/rupa/z $Z_HOME
fi
. $Z_HOME/z.sh

### ---------------------------------------------------------------------------
### Load machine-specific config files
### ---------------------------------------------------------------------------

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Customize to your needs...
if [ -f $HOME/.bashrc.local ]; then
    source $HOME/.bashrc.local
fi

